[build] 
  publish = "dist"
  command = "npm run build"

[dev] 
  publish = "dist"
  command = "npm run dev"




[[redirects]]
  from = "/images/tiny/*"
  to = "/.netlify/images/?w=10&h=10&fit=crop&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/small/*"
  to = "/.netlify/images/?w=500&h=500&fit=crop&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/medium/*"
  to = "/.netlify/images/?w=600&h=600&fit=crop&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/large/*"
  to = "/.netlify/images/?w=700&h=700&fit=crop&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/original/*"
  to = "/.netlify/images/:splat"
  status = 200
  